
DEFAULT_MODEL = "QuantFactory/dolphin-2.9-llama3-8b-GGUF"
DEFAULT_QUANT_LARGE = "*Q8_0.gguf"
DEFAULT_QUANT_BALANCED = "*Q4_K_M.gguf"
DEFAULT_QUANT_SMALL = "*Q2_K.gguf"
DEFAULT_TEMPERATURE = 0.0
DEFAULT_MAX_RETRIES = 8
