
DEFAULT_MODEL = "NousResearch/Hermes-2-Pro-Llama-3-8B-GGUF"
DEFAULT_QUANT_LARGE = "*Q8_0.gguf"
DEFAULT_QUANT_BALANCED = "*Q5_K_M.gguf"
DEFAULT_QUANT_SMALL = "*Q2_K.gguf"
DEFAULT_TEMPERATURE = 0.0
DEFAULT_MAX_RETRIES = 8
